/*
 * User Benefit Cost Calculation Api
 *
 * Api to support employee benefit cost calculations
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using BenefitsApi.Client.Client;
using BenefitsApi.Client.Api;
// uncomment below to import models
//using BenefitsApi.Client.Model;

namespace BenefitsApi.Client.Test.Api
{
    /// <summary>
    ///  Class for testing UsersApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class UsersApiTests : IDisposable
    {
        private UsersApi instance;

        public UsersApiTests()
        {
            instance = new UsersApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UsersApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' UsersApi
            //Assert.IsType<UsersApi>(instance);
        }

        /// <summary>
        /// Test UsersGet
        /// </summary>
        [Fact]
        public void UsersGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.UsersGet();
            //Assert.IsType<GetUserDtoIReadOnlyCollectionApiResponse>(response);
        }

        /// <summary>
        /// Test UsersIdGet
        /// </summary>
        [Fact]
        public void UsersIdGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int id = null;
            //var response = instance.UsersIdGet(id);
            //Assert.IsType<GetUserDtoApiResponse>(response);
        }

        /// <summary>
        /// Test UsersPost
        /// </summary>
        [Fact]
        public void UsersPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CreateUserDto? createUserDto = null;
            //instance.UsersPost(createUserDto);
        }
    }
}
