/*
 * User Benefit Cost Calculation Api
 *
 * Api to support employee benefit cost calculations
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using BenefitsApi.Client.Client;
using BenefitsApi.Client.Model;

namespace BenefitsApi.Client.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IUsersApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Get all users
        /// </summary>
        /// <exception cref="BenefitsApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>GetUserDtoIReadOnlyCollectionApiResponse</returns>
        GetUserDtoIReadOnlyCollectionApiResponse UsersGet();

        /// <summary>
        /// Get all users
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="BenefitsApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of GetUserDtoIReadOnlyCollectionApiResponse</returns>
        ApiResponse<GetUserDtoIReadOnlyCollectionApiResponse> UsersGetWithHttpInfo();
        /// <summary>
        /// Get user by id
        /// </summary>
        /// <exception cref="BenefitsApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>GetUserDtoApiResponse</returns>
        GetUserDtoApiResponse UsersIdGet(int id);

        /// <summary>
        /// Get user by id
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="BenefitsApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>ApiResponse of GetUserDtoApiResponse</returns>
        ApiResponse<GetUserDtoApiResponse> UsersIdGetWithHttpInfo(int id);
        /// <summary>
        /// Create user
        /// </summary>
        /// <exception cref="BenefitsApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createUserDto"> (optional)</param>
        /// <returns></returns>
        void UsersPost(CreateUserDto? createUserDto = default);

        /// <summary>
        /// Create user
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="BenefitsApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createUserDto"> (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> UsersPostWithHttpInfo(CreateUserDto? createUserDto = default);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IUsersApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Get all users
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="BenefitsApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetUserDtoIReadOnlyCollectionApiResponse</returns>
        System.Threading.Tasks.Task<GetUserDtoIReadOnlyCollectionApiResponse> UsersGetAsync(System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Get all users
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="BenefitsApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetUserDtoIReadOnlyCollectionApiResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<GetUserDtoIReadOnlyCollectionApiResponse>> UsersGetWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Get user by id
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="BenefitsApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetUserDtoApiResponse</returns>
        System.Threading.Tasks.Task<GetUserDtoApiResponse> UsersIdGetAsync(int id, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Get user by id
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="BenefitsApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetUserDtoApiResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<GetUserDtoApiResponse>> UsersIdGetWithHttpInfoAsync(int id, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Create user
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="BenefitsApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createUserDto"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task UsersPostAsync(CreateUserDto? createUserDto = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Create user
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="BenefitsApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createUserDto"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> UsersPostWithHttpInfoAsync(CreateUserDto? createUserDto = default, System.Threading.CancellationToken cancellationToken = default);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IUsersApi : IUsersApiSync, IUsersApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class UsersApi : IDisposable, IUsersApi
    {
        private BenefitsApi.Client.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="UsersApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public UsersApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="UsersApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public UsersApi(string basePath)
        {
            this.Configuration = BenefitsApi.Client.Client.Configuration.MergeConfigurations(
                BenefitsApi.Client.Client.GlobalConfiguration.Instance,
                new BenefitsApi.Client.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new BenefitsApi.Client.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = BenefitsApi.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="UsersApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public UsersApi(BenefitsApi.Client.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = BenefitsApi.Client.Client.Configuration.MergeConfigurations(
                BenefitsApi.Client.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new BenefitsApi.Client.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = BenefitsApi.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="UsersApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public UsersApi(HttpClient client, HttpClientHandler handler = null) : this(client, (string)null, handler)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="UsersApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public UsersApi(HttpClient client, string basePath, HttpClientHandler handler = null)
        {
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = BenefitsApi.Client.Client.Configuration.MergeConfigurations(
                BenefitsApi.Client.Client.GlobalConfiguration.Instance,
                new BenefitsApi.Client.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new BenefitsApi.Client.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = BenefitsApi.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="UsersApi"/> class using Configuration object.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public UsersApi(HttpClient client, BenefitsApi.Client.Client.Configuration configuration, HttpClientHandler handler = null)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = BenefitsApi.Client.Client.Configuration.MergeConfigurations(
                BenefitsApi.Client.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new BenefitsApi.Client.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = BenefitsApi.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="UsersApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public UsersApi(BenefitsApi.Client.Client.ISynchronousClient client, BenefitsApi.Client.Client.IAsynchronousClient asyncClient, BenefitsApi.Client.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = BenefitsApi.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public BenefitsApi.Client.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public BenefitsApi.Client.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public BenefitsApi.Client.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public BenefitsApi.Client.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public BenefitsApi.Client.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Get all users 
        /// </summary>
        /// <exception cref="BenefitsApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>GetUserDtoIReadOnlyCollectionApiResponse</returns>
        public GetUserDtoIReadOnlyCollectionApiResponse UsersGet()
        {
            BenefitsApi.Client.Client.ApiResponse<GetUserDtoIReadOnlyCollectionApiResponse> localVarResponse = UsersGetWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get all users 
        /// </summary>
        /// <exception cref="BenefitsApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of GetUserDtoIReadOnlyCollectionApiResponse</returns>
        public BenefitsApi.Client.Client.ApiResponse<GetUserDtoIReadOnlyCollectionApiResponse> UsersGetWithHttpInfo()
        {
            BenefitsApi.Client.Client.RequestOptions localVarRequestOptions = new BenefitsApi.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = BenefitsApi.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = BenefitsApi.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);



            // make the HTTP request
            var localVarResponse = this.Client.Get<GetUserDtoIReadOnlyCollectionApiResponse>("/Users", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UsersGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get all users 
        /// </summary>
        /// <exception cref="BenefitsApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetUserDtoIReadOnlyCollectionApiResponse</returns>
        public async System.Threading.Tasks.Task<GetUserDtoIReadOnlyCollectionApiResponse> UsersGetAsync(System.Threading.CancellationToken cancellationToken = default)
        {
            BenefitsApi.Client.Client.ApiResponse<GetUserDtoIReadOnlyCollectionApiResponse> localVarResponse = await UsersGetWithHttpInfoAsync(cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get all users 
        /// </summary>
        /// <exception cref="BenefitsApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetUserDtoIReadOnlyCollectionApiResponse)</returns>
        public async System.Threading.Tasks.Task<BenefitsApi.Client.Client.ApiResponse<GetUserDtoIReadOnlyCollectionApiResponse>> UsersGetWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default)
        {

            BenefitsApi.Client.Client.RequestOptions localVarRequestOptions = new BenefitsApi.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };


            var localVarContentType = BenefitsApi.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = BenefitsApi.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);



            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<GetUserDtoIReadOnlyCollectionApiResponse>("/Users", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UsersGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get user by id 
        /// </summary>
        /// <exception cref="BenefitsApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>GetUserDtoApiResponse</returns>
        public GetUserDtoApiResponse UsersIdGet(int id)
        {
            BenefitsApi.Client.Client.ApiResponse<GetUserDtoApiResponse> localVarResponse = UsersIdGetWithHttpInfo(id);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get user by id 
        /// </summary>
        /// <exception cref="BenefitsApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>ApiResponse of GetUserDtoApiResponse</returns>
        public BenefitsApi.Client.Client.ApiResponse<GetUserDtoApiResponse> UsersIdGetWithHttpInfo(int id)
        {
            BenefitsApi.Client.Client.RequestOptions localVarRequestOptions = new BenefitsApi.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = BenefitsApi.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = BenefitsApi.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("id", BenefitsApi.Client.Client.ClientUtils.ParameterToString(id)); // path parameter


            // make the HTTP request
            var localVarResponse = this.Client.Get<GetUserDtoApiResponse>("/Users/{id}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UsersIdGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get user by id 
        /// </summary>
        /// <exception cref="BenefitsApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetUserDtoApiResponse</returns>
        public async System.Threading.Tasks.Task<GetUserDtoApiResponse> UsersIdGetAsync(int id, System.Threading.CancellationToken cancellationToken = default)
        {
            BenefitsApi.Client.Client.ApiResponse<GetUserDtoApiResponse> localVarResponse = await UsersIdGetWithHttpInfoAsync(id, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get user by id 
        /// </summary>
        /// <exception cref="BenefitsApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetUserDtoApiResponse)</returns>
        public async System.Threading.Tasks.Task<BenefitsApi.Client.Client.ApiResponse<GetUserDtoApiResponse>> UsersIdGetWithHttpInfoAsync(int id, System.Threading.CancellationToken cancellationToken = default)
        {

            BenefitsApi.Client.Client.RequestOptions localVarRequestOptions = new BenefitsApi.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };


            var localVarContentType = BenefitsApi.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = BenefitsApi.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("id", BenefitsApi.Client.Client.ClientUtils.ParameterToString(id)); // path parameter


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<GetUserDtoApiResponse>("/Users/{id}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UsersIdGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Create user 
        /// </summary>
        /// <exception cref="BenefitsApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createUserDto"> (optional)</param>
        /// <returns></returns>
        public void UsersPost(CreateUserDto? createUserDto = default)
        {
            UsersPostWithHttpInfo(createUserDto);
        }

        /// <summary>
        /// Create user 
        /// </summary>
        /// <exception cref="BenefitsApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createUserDto"> (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public BenefitsApi.Client.Client.ApiResponse<Object> UsersPostWithHttpInfo(CreateUserDto? createUserDto = default)
        {
            BenefitsApi.Client.Client.RequestOptions localVarRequestOptions = new BenefitsApi.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json",
                "text/json",
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
            };

            var localVarContentType = BenefitsApi.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = BenefitsApi.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = createUserDto;


            // make the HTTP request
            var localVarResponse = this.Client.Post<Object>("/Users", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UsersPost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Create user 
        /// </summary>
        /// <exception cref="BenefitsApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createUserDto"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task UsersPostAsync(CreateUserDto? createUserDto = default, System.Threading.CancellationToken cancellationToken = default)
        {
            await UsersPostWithHttpInfoAsync(createUserDto, cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        /// Create user 
        /// </summary>
        /// <exception cref="BenefitsApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createUserDto"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<BenefitsApi.Client.Client.ApiResponse<Object>> UsersPostWithHttpInfoAsync(CreateUserDto? createUserDto = default, System.Threading.CancellationToken cancellationToken = default)
        {

            BenefitsApi.Client.Client.RequestOptions localVarRequestOptions = new BenefitsApi.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json", 
                "text/json", 
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
            };


            var localVarContentType = BenefitsApi.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = BenefitsApi.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = createUserDto;


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<Object>("/Users", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UsersPost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
