/*
 * User Benefit Cost Calculation Api
 *
 * Api to support employee benefit cost calculations
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BenefitsApi.Client.Model;
using BenefitsApi.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BenefitsApi.Client.Test.Model
{
    /// <summary>
    ///  Class for testing GetUserDtoApiResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetUserDtoApiResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetUserDtoApiResponse
        //private GetUserDtoApiResponse instance;

        public GetUserDtoApiResponseTests()
        {
            // TODO uncomment below to create an instance of GetUserDtoApiResponse
            //instance = new GetUserDtoApiResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetUserDtoApiResponse
        /// </summary>
        [Fact]
        public void GetUserDtoApiResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetUserDtoApiResponse
            //Assert.IsType<GetUserDtoApiResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }

        /// <summary>
        /// Test the property 'Success'
        /// </summary>
        [Fact]
        public void SuccessTest()
        {
            // TODO unit test for the property 'Success'
        }

        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }

        /// <summary>
        /// Test the property 'Error'
        /// </summary>
        [Fact]
        public void ErrorTest()
        {
            // TODO unit test for the property 'Error'
        }
    }
}
