/*
 * User Benefit Cost Calculation Api
 *
 * Api to support employee benefit cost calculations
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BenefitsApi.Client.Model;
using BenefitsApi.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BenefitsApi.Client.Test.Model
{
    /// <summary>
    ///  Class for testing GetUserDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetUserDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetUserDto
        //private GetUserDto instance;

        public GetUserDtoTests()
        {
            // TODO uncomment below to create an instance of GetUserDto
            //instance = new GetUserDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetUserDto
        /// </summary>
        [Fact]
        public void GetUserDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetUserDto
            //Assert.IsType<GetUserDto>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'FirstName'
        /// </summary>
        [Fact]
        public void FirstNameTest()
        {
            // TODO unit test for the property 'FirstName'
        }

        /// <summary>
        /// Test the property 'LastName'
        /// </summary>
        [Fact]
        public void LastNameTest()
        {
            // TODO unit test for the property 'LastName'
        }
    }
}
