/*
 * User Benefit Cost Calculation Api
 *
 * Api to support employee benefit cost calculations
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BenefitsApi.Client.Model;
using BenefitsApi.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BenefitsApi.Client.Test.Model
{
    /// <summary>
    ///  Class for testing CreateUserDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateUserDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateUserDto
        //private CreateUserDto instance;

        public CreateUserDtoTests()
        {
            // TODO uncomment below to create an instance of CreateUserDto
            //instance = new CreateUserDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateUserDto
        /// </summary>
        [Fact]
        public void CreateUserDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateUserDto
            //Assert.IsType<CreateUserDto>(instance);
        }

        /// <summary>
        /// Test the property 'FirstName'
        /// </summary>
        [Fact]
        public void FirstNameTest()
        {
            // TODO unit test for the property 'FirstName'
        }

        /// <summary>
        /// Test the property 'LastName'
        /// </summary>
        [Fact]
        public void LastNameTest()
        {
            // TODO unit test for the property 'LastName'
        }
    }
}
