/*
 * User Benefit Cost Calculation Api
 *
 * Api to support employee benefit cost calculations
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = BenefitsApi.Client.Client.FileParameter;
using OpenAPIDateConverter = BenefitsApi.Client.Client.OpenAPIDateConverter;

namespace BenefitsApi.Client.Model
{
    /// <summary>
    /// GetUserDtoIReadOnlyCollectionApiResponse
    /// </summary>
    [DataContract(Name = "GetUserDtoIReadOnlyCollectionApiResponse")]
    public partial class GetUserDtoIReadOnlyCollectionApiResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetUserDtoIReadOnlyCollectionApiResponse" /> class.
        /// </summary>
        /// <param name="data">data.</param>
        /// <param name="success">success.</param>
        /// <param name="message">message.</param>
        /// <param name="error">error.</param>
        public GetUserDtoIReadOnlyCollectionApiResponse(List<GetUserDto> data = default, bool success = default, string message = default, string error = default)
        {
            this.Data = data;
            this.Success = success;
            this.Message = message;
            this.Error = error;
        }

        /// <summary>
        /// Gets or Sets Data
        /// </summary>
        [DataMember(Name = "data", EmitDefaultValue = true)]
        public List<GetUserDto> Data { get; set; }

        /// <summary>
        /// Gets or Sets Success
        /// </summary>
        [DataMember(Name = "success", EmitDefaultValue = true)]
        public bool Success { get; set; }

        /// <summary>
        /// Gets or Sets Message
        /// </summary>
        [DataMember(Name = "message", EmitDefaultValue = true)]
        public string Message { get; set; }

        /// <summary>
        /// Gets or Sets Error
        /// </summary>
        [DataMember(Name = "error", EmitDefaultValue = true)]
        public string Error { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetUserDtoIReadOnlyCollectionApiResponse {\n");
            sb.Append("  Data: ").Append(Data).Append("\n");
            sb.Append("  Success: ").Append(Success).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("  Error: ").Append(Error).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
